---
- name: Start a container on Proxmox
  hosts: proxmox
  become: false
  tasks:
    - name: Start the LXC container
      community.general.proxmox:
        node: "{{ lookup('env', 'proxmox_host') }}"
        api_user: "{{ lookup('env', 'proxmox_user') }}"
        api_token_id: "{{ lookup('env', 'proxmox_api_key') }}"
        api_token_secret: "{{ lookup('env', 'proxmox_api_secret') }}"
        state: started
        vmid: "101"
        validate_certs: no
      register: start_result

    - name: Display result
      debug:
        var: start_result
