---
- name: Start a container on Proxmox
  hosts: proxmox
  become: false
  tasks:
    - name: Ensure Proxmox API is reachable
      uri:
        url: "https://{{ lookup('env', 'proxmox_host') }}:8006/api2/json"
        method: GET
        validate_certs: no
      register: api_status
      failed_when: api_status.status != 200

    - name: Verkrijg ticket voor Proxmox API
      community.general.proxmox:
        api_user: "{{ lookup('env', 'proxmox_user') }}"
        api_password: "{{ lookup('env', 'proxmox_password') }}"
        api_host: "{{ lookup('env', 'proxmox_host') }}"
        validate_certs: false
        state: present
      register: proxmox_ticket

    - name: Toon de Proxmox ticketinformatie
      debug:
        var: proxmox_ticket  

    - name: Start the LXC container
      community.general.proxmox:
        node: "{{ lookup('env', 'proxmox_host') }}"
        api_user: "{{ lookup('env', 'proxmox_user') }}"
        api_password: "{{ lookup('env', 'proxmox_password') }}"
        api_host: "{{ lookup('env', 'proxmox_host') }}"
        state: started
        vmid: "101"
        validate_certs: no
      register: start_result

    - name: Display result
      debug:
        var: start_result
